// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uynkqxzjxbaqjafaybhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5bmtxeHpqeGJhcWphZmF5YmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTc5NTMsImV4cCI6MjA3MDQ5Mzk1M30._jd96uPVe3Mw6T807a7X8OWAY3NZi0TEJPq_47pukS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});